### ISSUE TITLE
No ability to remove from course

### ISSUE THREAD

**Issue by 2shediac** [bynare/moodle-enrol_auto#13]
After loading and enabling the enrolment method, and then adding it to a course, there is no option to delete the method from a course.

Using version: 2017091400 on Moodle 3.4

![enrol](https://user-images.githubusercontent.com/16323254/40915770-47ffde4e-67cb-11e8-88d5-648854aa9c44.png)

**Comment by bynare** [comment]
This has been addressed in the 3.5 version ;)
