### ISSUE TITLE
Can't translate the privacy message in AMOS

### ISSUE THREAD

**Issue by ralf-krause** [bynare/moodle-enrol_auto#16]
Hi,
I translated all the text strings of the plugin enrol_auto for the german lang pack. I found that the privacy message is missing. Do you think that you uploaded the latest version into the Moodle plugin database?
`$string['privacy:metadata'] = 'The auto enrolment plugin does not store any personal data.';`
Ralf

**Comment by bynare** [comment]
Hi @ralf-krause - I just updated the plugin on the Moodle plugin database to include the privacy functionality ;) You should now be able to translate the string - once you've got all the strings translated, feel free to add the langpack here and I'll include it in the next release of the plugin!

Cheers,
Eugene.

**Comment by ralf-krause** [comment]
Hi Eugene 
thank you for your quick responce for this. You updated the files but not the version.php on github.com.
Ralf
