### ISSUE TITLE
Guest access overrides Auto enrol

### ISSUE THREAD

**Issue by Connor-Overt** [bynare/moodle-enrol_auto#19]
If you have a course with both auto-enrol and guest access enabled. 

The auto-enrol plugin does not enrol authenticated users. 

As soon as Guest access is removed it enrols as expected. Is it possible to allow authenticated users (who are not guest) to be enrolled on a course when viewing even though Guest access is enabled? 

This would allow institutions to monitor which authenticated users have accessed the course and would be useful from a statistical standpoint.

Thank you

Kind regards

Connor

**Comment by bynare** [comment]
Hi @Connor-Overt 

Auto-enrolling autenticated users is the main point of this plugin :)

I just tested and it definitely enrols a user (upon course view) when both Guest access and auto enrol plugin is enabled.

Can you provide steps on how to reproduce what you're seeing?

Thanks!
