### ISSUE TITLE
Enrol_auto doesn't work with Totara 17 / PHP 8

### ISSUE THREAD

**Issue by IrmaBoksEek** [bynare/moodle-enrol_auto#36]
Hi,
we would like to keep on using this plugin for our Totara customers, but at this point we can not use it after an upgrade. Is there any plan to adjust this for the newer Totara / PHP versions?
Thanks!
Irma

**Comment by danmarsden** [comment]
copying in an error received via email related to this:

Fatal error: Declaration of enrol_auto_plugin::try_autoenrol(stdClass $instance) must be compatible with enrol_plugin::try_autoenrol(stdClass $instance, bool $preventredirect = true) in /usr/share/nginx/html/server/enrol/auto/lib.php on line 190

**Comment by SashaAnastasi** [comment]
Kia ora IrmaBoksEek, it looks like the TOTARA_13 branch has the correct code.

Can you confirm the branch your implementation is using?

**Comment by IrmaBE** [comment]
Hi Sasha,
thanks for pointing this out. I think this is a different version than we used. I am new to github and think that my techguys took the plugin from the Moodle plugin page. I'll ask right away to place the version you mentioned and will let you know the result.
Kind regards,
Irma
