### ISSUE TITLE
Enrol_auto doesn't work with Totara 18+ / PHP 8.1+

### ISSUE THREAD

**Issue by IrmaBoksEek** [bynare/moodle-enrol_auto#38]
Hi,
we would like to keep on using this plugin for our Totara customers, but at this point we can not use it after an upgrade of the PHP version. Is there any plan to adjust this for the newer Totara / PHP versions?
Thanks!
Irma

**Comment by danmarsden** [comment]
@IrmaBoksEek does this relate to your previous report #36 ? - the right branch to use for Totara is NOT the "main" branch here in github.

**Comment by danmarsden** [comment]
I've just renamed a few things and set the default branch to the TOTARA_13 one to hopefully make it clearer.

**Comment by IrmaBoksEek** [comment]
Hi Dan, thanks for your response. This TOTARA_13 version does not work with PHP 8.1, therefore I asked a similar question.

**Comment by danmarsden** [comment]
Can you please provide the errors you're seeing? I'm pretty sure we have this on a t19 site and it passes unit tests and doesn't throw any lint errors

**Comment by IrmaBoksEek** [comment]
Hi Dan,
I asked for the errors etc, but somehow the issue was solved and the plugin is working now at Totara 18 and PHP 8.1. We are not aware that we made any changes.
Sorry for the confusion.
Cheers,
Irma

**Comment by danmarsden** [comment]
Thanks for the update - I'd assume the dev got the wrong branch.. hopefully the renaming and changing of the default branches will help to prevent issues in future.
