### ISSUE TITLE
Auto enroll upon course view allowing guest access

### ISSUE THREAD

**Issue by ShellyMcCollum** [bynare/moodle-enrol_auto#8]
When auto enrollment method is configured for Course view, guests are being allowed to enter the course even if guest access is not enabled on the course. In the Enrollment methods screen, it lists 1 user as being enrolled via auto enrollment plugin, even though no users appear in the list of enrolled users. I'm assuming the one is the guest account.

This is problematic if you only want your course catalog to be visible to the public but want users to have to login before they can access the courses.

**Comment by bynare** [comment]
Thanks for your report @ShellyMcCollum - I've made a small fix (and updated the tests) that addresses the issue you were seeing. The fix is on master, as well as MOODLE_35_STABLE.

Regards,
Eugene.

**Comment by bynare** [comment]
Thanks @mkiehl - I've now also prevented guest enrolment for login, as well as activity view.
